### PR TITLE
add lua-curl live server tests to travis CI

### PR DESCRIPTION
**Pull request by nihildeb**
I apologize that this comes as 16 separate commits. I attempted to roll it up, but since I forgot to make a branch before I started, my git-fu is not up to the task. The only existing file I have touched is the .travis.yml, so this at least won't break anything :)

I have added documentation for what I have done here. You can preview it in my repo:

https://github.com/nihildeb/civetweb/tree/master/test/ci_tests

### CODE REVIEW

**Comment by mattyclarkson** [comment]
```
git reset master
git add .travis.yml
git commit
```

**Comment by nihildeb** [comment]
sorry, is that something you want me to do? the pull request is correct I think, although sloppy (sry again). the travis.yml is correct the diff, and the other files are all needed to support the CI tests.

**Comment by nihildeb** [comment]
the reason I had trouble and couldn't consolidate as that I had to push to my fork several times. to test the CI integration. reseting to master doesn't work in that situation I think?

**Comment by bel2125** [comment]
I do not really care about if it is one commit or 42. 

I would like a little explanation of the code. How does a Lua curl live server test work in principle?
From what I understood from reading the files:
- the travis.yml file calls three *.sh files, two for setting up a test environment, one for the actual test
- the actual test (run_ci_tests.sh) calls something called busted, that I don' know
- this probably calls *.lua file in a test/ci_tests sub directory?
- test/ci_tests/01_basic/basic_spec.lua uses test/ci_tests/civet.lua
- test/ci_tests/civet.lua starts and stops the server executable, that has been built before

What does the binary file 
https://github.com/nihildeb/civetweb/blob/master/civetweb_test
do? Where is it called?

**Comment by bel2125** [comment]
And how can I actually trigger a test run?

**Comment by nihildeb** [comment]
The files:
setup_lua.sh just downloads lua and luarocks from websites and builds them on the travis server
install_rocks.sj just does luarocks install busted and lua-curl modules
run_tests calls busted (a spec framework for lua)  http://olivinelabs.com/busted/

busted searches for _spec.lua recursively in test/ci_tests/ and runs them

the binary civetweb_test is not called by me. it's just what you get when you run make unit_test in the civetweb Makefile. If I checked that in, it was an accident. I tried to run it, but it didn't work for me. Are there working unit tests for the project? I figured some basic functional tests would be good for the project in any case...

If you want to run the tests, just sign up on travis https://travis-ci.org/
Follow their instructions and enable it on this repo. Then the tests will run in about a minute, every time you check in, or anytime someone sends a pull request (travis automerges and attempts to build). The scripts I wrote are made for Ubuntu 12.04 since that is what Travis is running. I didn't do anything special, it's just Lua 5.2.4 from the distribution, luarocks and a few rocks. I imagine it will work on anything Posixy/Bashy. None of it requires sudo and runs it's own Lua from a directory inside .travis/lua. If you have a Linux/OSX computer you can try it by firing off the scripts in the order they appear in the .travis.yml

**Comment by nihildeb** [comment]
civetweb_test should in any case be deleted and added in the .gitignore I think

**Comment by mattyclarkson** [comment]
@nihildeb, yeah if you run those commands it'll squash all your commits into one commit. If you want to decide what to commit do `git add -p .` as the last command and you can decide what you want to add into each commit.

**Comment by bel2125** [comment]
I removed the civetweb_test file, signed up at travis and enabled the repository.
It should run automatically before a pull request, but is there some way to run it *just now* on the current repository - a 'run' button?

**Comment by nihildeb** [comment]
you have to push as far as I know

**Comment by nihildeb** [comment]
add civetweb_test to the .gitignore and push :)

**Comment by bel2125** [comment]
Seems to work, thank you:

    2 minutes ago
    master d264808
    Clean usage of const/not const mg_context* and mg_connection* handles in the API.
    1
    Build created successfully

**Pull request merged**
