### PR TITLE
Appveyor fix

### PR DESCRIPTION
**Pull request by mattyclarkson**
This branch does various things to fix up the build on Appveyor and Windows in general:
  * It adds more output to the mingw download log
  * It uploads the mingw download log as an artefact
  * It uploads the CMake cache as an artefact
  * It fixes up the tests by correcting the environment path and build symbols

### CODE REVIEW

**Comment by mattyclarkson** [comment]
@bel2125, I've optimised the Windows build as much as possible, it caches the MinGW compiler between builds - the appveyor check took 17min and 42 seconds.

When we change the `appveyor.yml` script or the `mingw.cmd` this will invalidate the cache and the next appveyor build will take longer due to it re-downloading the compiler. For example, the current appveyor uses 4.9.2 but we should probably change that to 5.1.0 - that would incur a one time cost of rebuilding the appveyor compiler cache.

Hopefully, we can keep the master green by making sure all PRs pass the checks.

**Comment by bel2125** [comment]
Does it also executes the full unit-test?

The check here in this pull requests says everything is OK -> I merge it.
The Appveyor banner in README.md currently states "failed" - maybe this takes a while to update (although it also said "pending" once). ... 

... Now (after 3 minutes) the state is pending ... let's wait ... 

... Now I got a build-failed mail:
https://ci.appveyor.com/project/bel2125/civetweb/build/15/job/3c7y23pycvm80hhp

    Error pushing artifact: The operation has timed out
    Command exited with code 2

Whatever this means.

And the banner again switches to "failing".

**Comment by bel2125** [comment]
Now the PR passed the test, but in the end, the build still failed.

**Comment by mattyclarkson** [comment]
It executes the CTest tests. i.e. the ones in `test/private.c` and `tests/public.c`. The tests need to be ported from `unit_test.c` and all the other tests that are littered around need to be integrated into CTest. This will be the transitional phase I was talking about

The status badge on the README.md is for the _`master`_ branch. The checks here are for the tip of the pull request. You can see the tick mark next to the 4a2e52b commit above. That means that if you merge the PR then it will make the `master` stable. In this case when you merged the branch the uploading of the `mingw-download.log` file failed to the Appveyor website. This is due to the Appveyor instance under the `bel2125` project didn't have the MinGW cache in place. I can tests and fix that up.

Once that is fixed it should be all sorted.

**Comment by mattyclarkson** [comment]
@bel2125, I _think_ this is a false positive. It worked on my [appveyor instance](https://ci.appveyor.com/project/mattyclarkson/civetweb/build/129/job/qhhe4agqff0ilu6s#L31) just now. The upload of the `mingw-download.log` completed.

If you go to the [build](https://ci.appveyor.com/project/bel2125/civetweb/build/15/job/3c7y23pycvm80hhp) you should be able to rebuild the commit. See if it completes.

**Pull request merged**
