### PR TITLE
Added support for TRACE HTTP Method

### PR DESCRIPTION
**Pull request by cdbishop**

### CODE REVIEW

**Comment by bel2125** [comment]
This change only adds TRACE to the methods that are *in principle* allowed.
The support for this method still needs to be added in `handle_request`.

The server needs to generate a response according to
http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.8

Do you plan to implement this handling method as well?

**Comment by bel2125** [comment]
I checked with curl that the TRACE method is usually not implemented / deactivated in all web sites I found - Apache, nginx, Google, Microsoft - all servers return 403 Forbidden, 405 Method Not Allowed or 501 Not Implemented to a TRACE request.

TRACE is not activated, because of security concerns:
http://www.cgisecurity.com/whitehat-mirror/WH-WhitePaper_XST_ebook.pdf

What do you do with this method?

**Comment by bel2125** [comment]
> *No description provided.*

Your original request does not contain a description.
Please describe the problem and the solution.

**Comment by cdbishop** [comment]
The problem I had was that TRACE requests where returning 500 server error. (whereas I need the return to be 501) I've just realized that this has already been fixed in the head. I was using the 1.6 release which I realise now is quite old

(this change wouldn't have been correct either way I've realized now)

Is there currently an expected time-frame for the next release?

**Comment by bel2125** [comment]
> Is there currently an expected time-frame for the next release?

I'm currently evaluating the open issues and postponing larger enhancements until after the next release. I need to do some testing and currently plan to finish this release in April.

An unsolved problem for this release is that I can not build and test for Mac OS.

**Pull request closed without merging**
