### PR TITLE
Some source checker corrections

### PR DESCRIPTION
**Pull request by hansipie**
I've added some "if !NULL" tests. I've removed all uses of "assert" (it was a little bit brutal). I've tried to set return values the same way it's already done for each ones, thank you for checking if it's well done.
And i've added the solarisfixes.h file in the tird party folder. Feel free to remove it if the licence is not compatible to the MIT.

### CODE REVIEW

**Comment by bel2125** [comment]
This can't be merged automatically by github, so I have to look through it and I also must have a look how to handle the BSD licensed code parts for solaris. I will do this later this week or during the weekend.

**Comment by hansipie** [comment]
ok, no pb :)

**Comment by hansipie** [comment]
Ok ...I will make the test (comments on solarisfix) next monday.

**Comment by hansipie** [comment]
Should I close this request and make a cleaner one removing the soloaris header file ?

**Comment by bel2125** [comment]
I think I have merged the important commits manually now (i.e., the commits not related to "solarisfixes.h"). Unfortunately your fork seems to be so different from my repository, that github could not merge it automatically (than the request is also closed automatically). 

I can not automatically compare it either, so I am not sure if I already got everything.
If you could have a look and you are sure, then please close the request (otherwise I will check and close it myself later).

**Comment by hansipie** [comment]
Your merge is ok, but here is only one thing missing: 
static __inline void   mg_free(void * a)               {free(a); a = NULL;}

... the reset of "a" to "NULL"

I close the request.

**Comment by bel2125** [comment]
I have not merged this, because I think this does not work like you might expect:

If the function is not inline, it will reset the argument of the mg_free function, which is a copy on the stack. Just after this, the function returns and the copy on the stack is no longer valid - the variable outside has never been reset to NULL, only the temporary copy.

Now from my understanding, if the function is inline, it must work exactly like if it were not inline.
In contrast to a macro: `#define mg_free(a) {free(a); a = NULL}` would differently and reset the outer variable.

**Comment by bel2125** [comment]
I just saw, you have pull request #127 for the `a = NULL;` in
`static __inline void mg_free(void * a) {free(a); a = NULL;}`
topic. Let's continue to discuss this there.

**Pull request closed without merging**
