### PR TITLE
Reset pointer

### PR DESCRIPTION
**Pull request by hansipie**
Set pointer to NULL after delete.

### CODE REVIEW

**Comment by bel2125** [comment]
See comment https://github.com/bel2125/civetweb/pull/124#issuecomment-103920218 to pull request #124 

I will test this, and post the result here.

**Comment by bel2125** [comment]
Try this:

    static __inline void mg_free(void *a) { free(a); a = NULL; }

    void testfunc(void)
    {
        void * test;
        test = mg_malloc(12345);
        printf("before: %x\n", test);
        mg_free(test);
        printf("after: %x\n", test);
    }


Result:
The same value is printed before and after, just like explained in https://github.com/bel2125/civetweb/pull/124#issuecomment-103920218. The `a=NULL;` only affects the temporary variable `a` on the stack, not the `test` variable in the `testfunc`.
This is why I did not merge the `a=NULL;` in #124 - it is a statement without effect.

**Comment by bel2125** [comment]
Same test with #define:

    #define mg_free(a) { free(a); a = NULL;}

    /* comment:  #define free DO_NOT_USE_THIS_FUNCTION__USE_mg_free  */

    void testfunc(void)
    {
        void * test;
        test = mg_malloc(12345);
        printf("before: %x\n", test);
        mg_free(test);
        printf("after: %x\n", test);
    }

Result:
The "after" value is 0, again like explained in https://github.com/bel2125/civetweb/pull/124#issuecomment-103920218.

I also checked the disassembly in both cases - the function is really inline in the first case.

**Comment by hansipie** [comment]
Yes, you are right ... I was not expecting this behaviour. For me, inline functions was supposed to make the compilator do code substitution. But going depth in documentations it's not that simple: depending of the compilator, of the code, and whatever it's done or not.

On another hand in the code, after the calling of mg_free() we set the pointer to NULL .. and sometimes not. I guess we need this "NULL-ification".
Doing something like ...
    static inline void mg_free(void **a) { free(*a); *a = NULL;}
... seems to do what i was expecting.
But ok ... i will make some tests on my side to be sure. 

Use inline functions is really mandatory ?

**Comment by bel2125** [comment]
> ... For me, inline functions was supposed to make the compilator do code substitution. ...

Inline functions do not really do code substitutions, as macros do,
Inline functions are just ordinary functions - declaring them as inline tells the compiler not to generate a jump/call to one implementation and not to generate a full stack frame, which is a pure performance issue - it should not change the behavior of the function.



> On another hand in the code, after the calling of mg_free() we set the pointer to NULL .. 
> and sometimes not. I guess we need this "NULL-ification".

If I made it consistently (not all the code is mine, and maybe I forgot some lines), it should be like this:

I do not set the pointer variable to NULL, if it is a local variable that runs out of scope some lines later.
I do set the pointer to NULL if it is a global variable, or a member in a shared structure.

Examples:

    int func1(struct t_my3Dvector * v)
    {
        int res = 0;
        if (v) {
            res = somefunc(v->x, v->y, v->z);
            free(v);
            /* don't set v to NULL here - it runs out of scope soon. 
             * Nothing we do with v will be visible outside this function.
             */
        }
        return res;
    }

    int func2(struct t_context *c)
    {
        int res = 0;
        if (c) {
            res = otherfunc(c->data_ptr);
            free(c->data_ptr);
            c->data_ptr = NULL; /* c runs out of context, but it is just a copy of the address 
                                 * of a struct t_context * variable owned by the caller of func2. 
                                 * Set the c->data_ptr member to NULL so the caller does not 
                                 * (directly or indirectly) access an invalid address afterwards. 
                                 */
        }
        return res;
    }



> Doing something like ...
> `static inline void mg_free(void** a) { free(*a); *a = NULL;}`
> ... seems to do what i was expecting.

Yes, but then you would have to change all calls from `mg_free(ptr)` to `mg_free(&ptr)`, which would be incompatible and unusual - it should probably not be called `free` then.
Also the macro would do what you expected without having to add the & at the caller side.
In C++ you could use a mg_free(void * &a) - this might be the nicest way to set a to NULL - but this does not work for C.

Anyway, I think you are trying to solve a problem here, that probably does not exist currently - resetting the pointers to NULL is done at the required places in the code (see description and func1/func2 example above).

> Use inline functions is really mandatory ?

Not really mandatory.
But it seems to be a good choice - as fast as a macro, but type prove and better to debug.

**Comment by hansipie** [comment]
Always set NULL after a free is some kind of old habit (and it's reported as an error by the source checker i use if it's not done ... perhapse there is a lack here), but yes i agree, it's not always usefull ...but it does not arm, so...

In fact i would not have do it like this. As it is usefull to redefine free, malloc, etc ... for memory debugging purpose (i.e.<code> #if defined(MEMORY_DEBUGGING) </code>) and to be able to easily switch to normal mode,  the <code>#define</code> way would be my choice. 
...Nevermind ... I close this request. thank you.

**Pull request closed without merging**
