### PR TITLE
Feather xml

### PR DESCRIPTION
**Pull request by wiseoldman95**
Added the XML generator. We did not discuss it much, so feel free to suggest changes before merging.

### CODE REVIEW

**Comment by wiseoldman95** [comment]
Do NOT merge, several bugs found.

**Comment by wiseoldman95** [comment]
No more known bugs.

**Comment by wiseoldman95** [comment]
It makes sense to move the XMLl generator to a separate file, should I do that?

**Comment by wiseoldman95** [comment]
I have added some extra features which require testing. I am closing this pull request and opening a new one when I feel my code is production-ready. I am maintaining a repo here: https://github.com/wiseoldman95/FeatherXML

**Comment by bel2125** [comment]
> It makes sense to move the XMLl generator to a separate file,
> should I do that?

Yes, please.
Better do not integrate the changes directly into civetweb.c, but let it be
an optional .c file and an additional.h file.

Probably it is better to discuss the details either on the civetweb google
mailing list, or directly by email, than to discuss it in issues and pull
requests.

**Pull request closed without merging**
