### PR TITLE
Fix unused variable when DEBUG is not defined

### PR DESCRIPTION
**Pull request by kainjow**

### CODE REVIEW

**Comment by bel2125** [comment]
I currently need this variable to test the server in the debugger:

The code `int err = ERRNO;` translates to `err = GetLastError();` in Windows, and this is the only way I know to see the value of GetLastError in the debugger when I put a breakpoint below.
I can replace this in some days, but not at the moment while I'm working at the timeouts.

**Comment by kainjow** [comment]
How about surrounding those two lines with #ifdef DEFINE ?

**Comment by bel2125** [comment]
If it's just for the warning, a `(void)err;` would do as well.

Unfortunately both `send` and `recv` return completely different codes in case of error between Linux and Windows, so it is not so simple to get a cross platform error handling code correctly, and to force all kinds of errors to test it.

**Comment by kainjow** [comment]
This can be closed?

**Comment by bel2125** [comment]
The "unused" warning is gone. The code is marked with a "TODO" (but not with high priority) to check the timeout error codes for Linux and Windows.
I think we can close it - I will pick up the TODO later.

**Pull request closed without merging**
