### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by bel2125**
For the moment: Add CMAKE Files, but let the rest unchanged

### CODE REVIEW

**Comment by bel2125** [comment]
Version 1.7 is released now, and I plan to switch to CMake with version 1.8
Most commits are merged. I did not merge the "Remove" commits ... 

 @mattyclarkson Remove third party source … 	6cfce2b
 @mattyclarkson Remove the Makefiles … 	44a5f78
 @mattyclarkson Remove the Visual Studio Solution … 	4cba833
 @mattyclarkson Remove Qt build … 	662d599

... at least for the moment, so I can continue working in the current way until everything is working in the new way, and everything is tested.

I am not sure with the following commits ...

 @mattyclarkson CMake build for SQLite … 	1966b23
 @mattyclarkson CMake build for Lua SQLlite … 	702eacb
 @mattyclarkson CMake build for Lua Filesystem … 	64cac8b
 @mattyclarkson CMake build for Lua XML … 	5f30a91

... in particular since I kept the third party source and did not merge 6cfce2b.
Firs, I have to understand in detail how CMake handles the third party components.

**Comment by mattyclarkson** [comment]
@bel2125, thanks for getting started on this. good to get this upstreamed.

The "Remove" commits were just so that I could concentrate on getting the source built with CMake and avoid any conflicts with the previous build system. Ideally they _should_ occur because all of the other build systems and third party source should be handled by CMake, however, there could be transitional period between 1.7 and 1.8 where we phase them out as you become confident with CMake.

The CMake build for the third party components uses [ExternalProject](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html) to download the source and build it into static libraries that can be included into the built library. You can see the code [here](https://github.com/vcatechnology/civetweb/blob/b7e3c518fb5404b5eee795c6dc5a35f61a7a6913/src/CMakeLists.txt#L113-134) as an example.

I'll put a bit of work in to rebase the branch today.

**Comment by mattyclarkson** [comment]
The CMake build is missing certain things at the moment:

  - Need to port the unit tests to CTest
    - Can do this piece by piece until we get a high enough coverage percentage.
  - Currently the travis and appveyor do the minimum build of civetweb, the following things need to be enabled and tested in the builds
    - Websockets
    - C++ bindings
    - IPv6
    - Lua
      - This will be a big one as it changes over building Lua support from downloaded source

I think the best thing to do is that I push up PRs for each of those individually and slowly phase out the old stuff? Things can be worked on in parallel then by different people if needed. I guess we could keep track of everything under #147?

**Comment by bel2125** [comment]
Yes, I need to have the current build on parallel for a while.

- Websockets
- C++ bindings
- IPv6

They should just be some defines. So this would be another build with the same code.

Let's postpone the Lua / third_party until all the other things are done.
One problem might be, that I did small patches to some of the external projects, and I don't know how to deal with them in the moment.

**Comment by kainjow** [comment]
Latest code doesn't work with OS X clang: `clang: error: no such file or directory: '/W4'`

Output shows:

    Performing Test HAVE_C_FLAG_W4
    -- Performing Test HAVE_C_FLAG_W4 - Success

Which is weird, not sure why that is being passed as a valid flag. If I surround it with `if (MSVC)` it works.

**Comment by mattyclarkson** [comment]
@kainjow, that is bizarre. The `clang` build on Linux is doesn't pick up that flag. I asked the guys at Travis to enable Mac OSX support but they are restructuring their backend so aren't adding new capacity right now.

I think wrapping it with MSVC is hiding a bug somewhere else - maybe the CheckCCompilerFlag.cmake is producing a false positive.

**Comment by kainjow** [comment]
@mattyclarkson maybe CMake is converting it into "-W4" which clang will then say `warning: unknown warning option '-WX'` but when added with "-Werror" it'll cause execution to fail.

Is this flag valid on any other compiler except MSVC? If not, the MSVC check is the simplest solution.

**Comment by kainjow** [comment]
Also, the check code doesn't compile through CMake, but it does with ./configure and make, so somehow their CMake config is behind. Probably will require an additional patch to maintain in civetweb.

**Comment by mattyclarkson** [comment]
@kainjow, `clang` on windows attempts to match the MSVC flags so could be that we want to keep it. It's again odd that `check` doesn't compile under Mac OSX with `clang` but does on `linux`. What generator are you building it with?

**Comment by kainjow** [comment]
@mattyclarkson no generator set, so just makefiles. I'm just calling `cmake` and `make` from the check source directory. I can look into it later.

**Comment by bel2125** [comment]
> I guess we could keep track of everything under #147?

So then we could actually close https://github.com/bel2125/civetweb/issues/94 and redirect to here?
Or do we have any further need for #94?

**Comment by mattyclarkson** [comment]
oh. sorry I got the numbers mixed up. I'd probably best to keep track of things under #94 and close this PR.

**Comment by bel2125** [comment]
OK. I close this issue.

Further discussion:

#94
=====

**Pull request closed without merging**
